### ISSUE TITLE
About the experiment results in your paper.

### ISSUE THREAD

**Issue by Zhaohuai-L** [jiaw-z/FeatureConsistentStereo#7]
Hi , Thanks a lot for your great work,Can I know how you tested in your Table1 about the PSMNet  Results? 
![image](https://user-images.githubusercontent.com/62138387/181021571-c0527288-a6c4-418b-bf8b-112b15df6eb8.png)

It has different results from the following papers:
Table3 in _Domain-invariant Stereo Matching Networks_
![image](https://user-images.githubusercontent.com/62138387/181021637-cb2216cd-c5bf-4bcd-a1fa-a4831e2114e4.png)
Table5 in _GraftNet: Towards Domain Generalized Stereo Matching with a Broad-Spectrum and Task-Oriented Feature_
![image](https://user-images.githubusercontent.com/62138387/181022134-0ca0fd20-ee45-4905-9d54-8f180436041c.png)

**Comment by jiaw-z** [comment]
> Hi , Thanks a lot for your great work,Can I know how you tested in your Table1 about the PSMNet Results? ![image](https://user-images.githubusercontent.com/62138387/181021571-c0527288-a6c4-418b-bf8b-112b15df6eb8.png)
> 
> It has different results from the following papers: Table3 in _Domain-invariant Stereo Matching Networks_ ![image](https://user-images.githubusercontent.com/62138387/181021637-cb2216cd-c5bf-4bcd-a1fa-a4831e2114e4.png) Table5 in _GraftNet: Towards Domain Generalized Stereo Matching with a Broad-Spectrum and Task-Oriented Feature_ ![image](https://user-images.githubusercontent.com/62138387/181022134-0ca0fd20-ee45-4905-9d54-8f180436041c.png)

We implement the PSMNet and evaluate the domain generalization performance. We report results of 3-pixel error rate. Similar results are also observed in other works. So we decide to report the results of our implemented PSMNet.
AcfNet: 
![image](https://user-images.githubusercontent.com/66359549/201968038-75eec026-5004-491b-bb64-fd448af2a0fc.png)
STTR:
![image](https://user-images.githubusercontent.com/66359549/201969099-d3e185f4-e077-402a-b4c7-f8f790489009.png)

**Comment by Zhaohuai-L** [comment]
OK, thanks for your reply.
